SPA_MVC_StudentApp/Controllers/ManageStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SPA_MVC_StudentApp.Controllers
{
    public class ManageStudentController : Controller
    {
        //
        // GET: /ManageStudent/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddStudent()
        {
            return PartialView("AddStudent");
        }

        public ActionResult EditStudent()
        {
            return PartialView("EditStudent");
        }

        public ActionResult ShowAllStudent()
        {
            return PartialView("ShowAllStudent");
        }

        public ActionResult DeleteStudent()
        {
            return PartialView("DeleteStudent");
        }


	}
}

SPA_MVC_StudentApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <base href="/">
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body data-ng-app="ApplicationModule">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Student management application", "Index", "ManageStudent", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="tableoptions"><a href="showstudents"> Show All Students </a></li>
                    <li class="tableoptions"><a href="addstudent"> Add New Student </a></li>
                    <li class="tableoptions"><a href="searchstudent"> Search Student </a></li>
                    <!--<li>@@Html.ActionLink("Add New Student", "addstudent", "", "", new { @@class = "btn-link" })</li> -->
                </ul>
            </div> -
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>
    <hr />
    <footer class="text-primary text-center">
        <p>&copy; @DateTime.Now.Year -Niladri Sekhar Dutta</p>
    </footer>
    
    @RenderSection("Scripts", required: false)
</body>
</html>